name: Crawl bonbanh.com
on:
  schedule:
    - cron: '15 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'crawling/'
jobs:
  crawl-data:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Crawl data
        run: |
          cd crawling/
          python3 run_bonbanh_spider.py